export const browseSortClickObj = {
    category: false,
    sort: false,
}
export const browseBtnTextObj = {
    categoryText: "All",
    sortText: "Select",
}
export const quantityChangeObj = {
    laptop: 0,
    rolexWatch: 0,
    headphones: 0,
    android: 0,
    iphone: 0,
    gamingPc: 0,
    appleWatch: 0,
    sunglass: 0,
    tie: 0,
    purse: 0,
    hoodBlack: 0,
    fadeHoodBlue: 0,
    lsBlack: 0,
    lsWhite: 0,
    ssPlaid: 0,
    pencils: 0,
    pens: 0,
    backpack: 0,
    notebook: 0,
    binders: 0,
    hammer: 0,
    drill: 0,
    eSaw: 0,
    wrench: 0,
    bandSaw: 0,
}
export const quantityObj = {
    laptop: 0,
    rolexWatch: 0,
    headphones: 0,
    android: 0,
    iphone: 0,
    gamingPc: 0,
    appleWatch: 0,
    sunglass: 0,
    tie: 0,
    purse: 0,
    hoodBlack: 0,
    fadeHoodBlue: 0,
    lsBlack: 0,
    lsWhite: 0,
    ssPlaid: 0,
    pencils: 0,
    pens: 0,
    backpack: 0,
    notebook: 0,
    binders: 0,
    hammer: 0,
    drill: 0,
    eSaw: 0,
    wrench: 0,
    bandSaw: 0,
}
export const cardCheckoutLimit = {
    laptop: 0,
    rolexWatch: 0,
    headphones: 0,
    android: 0,
    iphone: 0,
    gamingPc: 0,
    appleWatch: 0,
    sunglass: 0,
    tie: 0,
    purse: 0,
    hoodBlack: 0,
    fadeHoodBlue: 0,
    lsBlack: 0,
    lsWhite: 0,
    ssPlaid: 0,
    pencils: 0,
    pens: 0,
    backpack: 0,
    notebook: 0,
    binders: 0,
    hammer: 0,
    drill: 0,
    eSaw: 0,
    wrench: 0,
    bandSaw: 0,
}
export const productSubtotalObj = {
    laptop: 0,
    rolexWatch: 0,
    headphones: 0,
    android: 0,
    iphone: 0,
    gamingPc: 0,
    appleWatch: 0,
    sunglass: 0,
    tie: 0,
    purse: 0,
    hoodBlack: 0,
    fadeHoodBlue: 0,
    lsBlack: 0,
    lsWhite: 0,
    ssPlaid: 0,
    pencils: 0,
    pens: 0,
    backpack: 0,
    notebook: 0,
    binders: 0,
    hammer: 0,
    drill: 0,
    eSaw: 0,
    wrench: 0,
    bandSaw: 0,
}

export const clothesSizeClickObj = {
    hoodBlack: false,
    fadeHoodBlue: false,
    lsBlack: false,
    lsWhite: false,
    ssPlaid: false,
}

export const clothesSizeSelectedObj = {
    hoodBlack: 'M',
    fadeHoodBlue: 'M',
    lsBlack: 'M',
    lsWhite: 'M',
    ssPlaid: 'M',
}